### ISSUE TITLE
Axles Workstation has connectivity

### ISSUE THREAD

**Issue by JBB** [cs210/AXLES#2]
Hi team,
Your Windows reinstall appears to have worked.
cs210student/cs210a are the credentials.

As I leave it now, it is downloading an update.  You should be able to take it from here.

**Comment by akhand42** [comment]
Thanks, @JBB! Just checked it out. Everything seems to be working now.

**Comment by JBB** [comment]
Remember to stall everything you can on the D drive and clean up any legacy Windows update files if you start to run out of space on C.

**Comment by JBB** [comment]
Also, if it turns out you don't need the license key, you can send me a photo of the paper before throwing it away, so I can use it for future workstations.  If you do need it, go for it.
